export const schemas = {
  programs: {
    title: "院校项目",
    endpoint: "/api/programs",
    columns: [
      ["school", "学校"],
      ["college", "学院"],
      ["major", "专业"],
      ["program_type", "类型"],
      ["direction", "方向"],
      ["stage", "阶段"],
      ["date_text", "时间"],
      ["account", "账号"],
      ["password", "密码"],
      ["status", "状态"],
      ["note", "备注"],
    ],
    fields: [
      { key: "school", label: "学校", required: true },
      { key: "college", label: "学院" },
      { key: "major", label: "专业" },
      { key: "program_type", label: "类型", optionKey: "programTypes" },
      { key: "direction", label: "方向" },
      { key: "stage", label: "阶段", optionKey: "programStages" },
      { key: "date_text", label: "时间" },
      { key: "account", label: "账号" },
      { key: "password", label: "密码" },
      { key: "status", label: "状态", optionKey: "programStatuses" },
      { key: "note", label: "备注", type: "textarea", full: true },
    ],
  },
  professors: {
    title: "导师",
    endpoint: "/api/professors",
    fields: [
      { key: "name", label: "姓名", required: true },
      { key: "school", label: "学校" },
      { key: "college", label: "学院/组" },
      { key: "direction", label: "研究方向", full: true },
      { key: "email", label: "邮箱" },
      { key: "homepage", label: "主页" },
      { key: "status", label: "状态", optionKey: "professorStatuses" },
      { key: "note", label: "备注", type: "textarea", full: true },
    ],
  },
  materials: {
    title: "文件",
    endpoint: "/api/materials",
    fields: [
      { key: "name", label: "名称", required: true },
      { key: "category", label: "归类", optionKey: "categories" },
      { key: "related_professor", label: "关联导师", optionKey: "professors", allowEmpty: true },
      { key: "related_program", label: "关联院校", optionKey: "programs", allowEmpty: true },
      { key: "path", label: "本地路径", full: true },
      { key: "note", label: "备注", type: "textarea", full: true },
      { key: "pinned", label: "置顶", options: ["0", "1"] },
    ],
  },
  tasks: {
    title: "待办",
    endpoint: "/api/tasks",
    columns: [
      ["title", "事项"],
      ["scope", "范围"],
      ["due_date", "截止"],
      ["priority", "优先级"],
      ["status", "状态"],
      ["note", "备注"],
    ],
    fields: [
      { key: "title", label: "事项", required: true, full: true },
      { key: "scope", label: "范围" },
      { key: "due_date", label: "截止日期", type: "date" },
      { key: "priority", label: "优先级", optionKey: "taskPriorities" },
      { key: "status", label: "状态", optionKey: "taskStatuses" },
      { key: "note", label: "备注", type: "textarea", full: true },
    ],
  },
  questions: {
    title: "面试题",
    endpoint: "/api/questions",
    columns: [
      ["topic", "主题"],
      ["question", "问题"],
      ["answer", "答案要点"],
      ["tag", "标签"],
    ],
    fields: [
      { key: "topic", label: "主题", optionKey: "questionTopics" },
      { key: "question", label: "问题", type: "textarea", required: true, full: true },
      { key: "answer", label: "答案要点", type: "textarea", full: true },
      { key: "tag", label: "标签" },
    ],
  },
};
